config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/incrediblue'

  devise_for :users

  resources :products do
    resources :comments
  end
  resources :users
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  
  post 'static_pages/thank_you'
  
  post 'payments/create'
  

  root 'products#index'
  
  resources :orders, only: [:index, :show, :create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  
  def landing_page
    @featured_product = Product.first
    @products = Product.limit(3)
  end  
  
  
  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    ActionMailer::Base.mail(:from => @email,
        :to => 'jzamparas@gmail.com',
        :subject => "A new contact form message from #{@name}",
        :body => @message).deliver_now
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="container-fluid title">
	<div class="row form-row">
		<div class="col-xs-12 col-md-4 form-entry">
			<h1>This site was created with</h1>
			<p><%= image_tag("/assets/Ruby_on_Rails_logo.png", width: '150') %></p>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<div class="container">

<h1>Contact Us</h1>

<%= flash[:notice] %>

	<%= form_tag("/static_pages/thank_you") do %>
	<div class="row form-row">
		<div class="col-xs-12 col-md-4 form-entry">
			<div class="form-group">
				<%= label_tag :name, "Name" %>
				<%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
			</div>
			<div class="form-group">
				<%= label_tag :email, "Email Address" %>
				<%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email", type:'email', :required => true%>
			</div>
			<div class="form-group">
				<%= label_tag :message, "Message" %>
				<%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message" %>
			</div>
				<%= submit_tag("Send", class: "btn btn-default") %>
		</div>
	</div>
	<% end %>

</div>

app/views/static_pages/index.html.erb
<h1>Welcome to Bike Berlin</h1>
<h2>Your source for used bikes in Berlin</h2>
<%= image_tag("2.jpg" , class: "img-responsive ship") %>
<p>Welcome! The date and time is <%= Time.now %></p>

app/views/static_pages/landing_page.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
    <div class="item<%= " active" if product == @products.first %>">
      <%= image_tag(product.image_url) %>
      <div class="carousel-caption">
        <%= product.name %>
      </div>
        </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<%= params[:example_key].to_i * 10 %>

app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->

<div class="buttoncenter"><%= link_to 'Return to Home Page', static_pages_index_path, class: "btn btn-default" %></div>