config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/incrediblue'

  devise_for :users

  resources :products do
    resources :comments
  end
  resources :users
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  
  post 'static_pages/thank_you'
  
  post 'payments/create'
  

  root 'products#index'
  
  resources :orders, only: [:index, :show, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments
  
  def average_rating
    comments.average(:rating).to_f
  end
  
  validates :name, presence: true
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  # GET /products
  # GET /products.json
  
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("LOWER(name) LIKE ? OR LOWER(description) LIKE?", "%#{search_term.downcase}%", "%#{search_term.downcase}#")
    else
      @products = Product.all
    end
    respond_with @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").page(params[:page]).per_page(5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
    
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
	<% @comments.each do |comment| %>
		<div class="row">
			<hr>
			<p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
				<% if signed_in? && current_user.admin? %>
					<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
			</p>
			<p>
				<div class="rated" data-score="<%= comment.rating %>"></div>
			</p>
			<p><%= comment.body %></p>
		</div>
	<% end %>
</div>

app/views/products/_form.html.erb
<div class="col-xs-12 col-sm-12 col-lg-12 form">
  <%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
  
        <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="product-form">
      <div class="field form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :image_url %><br>
        <%= f.text_field :image_url, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :price %><br>
        <%= f.text_field :price, class: "form-control" %>
      </div>
      <div class="actions">
        <%= f.submit(class: "btn btn-default") %>
      </div>
    </div>
  <% end %>
</div>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
 
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Add a review" %><br>
      <%= f.text_area :body, class: "form-control" %>
    </p>
    
    <p>
      <div class="rating"></div>
    </p>
    
    <p>
      <%= f.submit "Submit", class: "btn btn-default" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-xs-12 col-sm-6 col-lg-4 product">
	<%= image_tag(product.image_url, class: "img-responsive img-rounded") %>
  <div class="col-lg-12">
  	<h1><strong><%= product.name %></strong></h1>
	</div>
	<div class="col-lg-12">
  	<p><%= product.description %></p>
	</div>
	<div class="col-lg-12">
  	<p>$<%= product.price %></p>
	</div>
	<div class="col-lg-12 crud1">
  	<%= link_to 'Show', product %>
  	<%= link_to 'Edit', edit_product_path(product) %>
  	<%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
</div>

app/views/products/edit.html.erb
<div class="container title" id="edit">

	<div class="row">
		<h1>Editing Product</h1>
	</div>

	<div class="row forms">

		<%= render 'form' %>

		<div class="product-paths">
			<%= link_to 'Show', @product %> |
			<%= link_to 'Back', products_path %>
		</div>

	</div>

</div>

app/views/products/index.html.erb
<div class="container-fluid title">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <h1 id="vinyls">Listing Yachts</h1>
  </div>
  
  
  <div class="container">
    <div class="row">
      <% cache(cache_key_for_products) do %>
        <%= render @products %>
      <% end %>
    </div>
  </div>
  <br>
  <div class="buttoncenter"><%= link_to 'New Product', new_product_path, class: "btn btn-default" %></div>

</div>

app/views/products/new.html.erb
<div class="container title" id="new">

	<div class="row">
		<h1>New Product</h1>
	</div>

	<div class="row forms">
		<%= render 'form' %>

		<div class="product-paths">
			<%= link_to 'Back', products_path %>
		</div>
	</div>

</div>

app/views/products/show.html.erb
<div class="container title">

<p id="notice"><%= notice %></p>

	<div class="col-xs-12 col-md-7">
		<div class="row product_show">
			<% cache @product do %>
				<h1>
		  		<%= @product.name %>
				</h1>
	
		
				<p>
		  		<center><%= image_tag(@product.image_url, class: "img-responsive img-rounded img-zoom", data_zoom_image: @product.image_url) %></center>
				</p>
		
				<p>
		  		<%= @product.description %>
				</p>
				<p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div></p>
		
				<p>
					<span id="price">$<%= @product.price %></span>
				</p>
		    <div class="paycrud">
		  		<%= link_to 'Edit', edit_product_path(@product) %> |
		  		<%= link_to 'Back', products_path %>
		       
		  		<%= form_tag "/payments/create" do %>
		    	<%= render 'shared/stripe_checkout_button' %>
		    	<%= hidden_field_tag(:product_id, @product.id) %>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
	
	<div class="col-xs-12 col-md-5">
		<div class="row product_comment">
			<h1>Reviews</h1>
			<%= render 'new_comment' %>
			<%= render 'comments' %>
	
			<div class="paginate"><%= will_paginate @comments %></div>
		</div>
	</div>

</div>