config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/incrediblue'

  devise_for :users

  resources :products do
    resources :comments
  end
  resources :users
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'
  
  post 'static_pages/thank_you'
  
  post 'payments/create'
  

  root 'products#index'
  
  resources :orders, only: [:index, :show, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<body>
  
<div class="container">
  <div class="navbar transparent navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <nav class="navbar-header navbar-inner">
          <button type="button" class="navbar-toggle"  data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="nav navbar-nav navbar-brand">
            <%= link_to "Yacht Club", products_url %>
          </div><!--end projectname-->
        </nav><!--end nav header-->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              <% else %>
                <%= link_to('Login', new_user_session_path) %>
              <% end %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About this site", static_pages_about_url %></li>
            <li><%= link_to "Browse Yachts", products_url %></li>
            <li><%= link_to "Orders", orders_url %></li>
            <li><%= link_to "Contact", static_pages_contact_url %></li>
            <li>
              <div class="form-group navsearch">
                <%= form_tag("/products", method: "get", class: 'navbar-form', role: 'search') do %>
                <%= text_field_tag(:q, "", placeholder: "Search", class: "form-control" ) %>
                <%= submit_tag("Search", class: "btn btn-default") %>
                <% end %>
              </div>
            </li>
          </ul>
        </div><!--end nav collapse-->
      </div><!--end container-->
    </div><!--end navbar-->
  </div><!--end container-->

<% if notice %>
    <p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
<% end %>
<% if alert %>
    <p id="alert" class="alert alert-info" role="alert"><%= alert %></p>
<% end %>

<%= yield %>


<footer class="container-fluid">
  <div class="footer">
    © Copyright John Zabaras 2016
  </div><!--end footer-->  
</footer>
</body>
</html>